server:
  servlet:
    context-path: / #msmupload
  port: 8061
spring:
  application:
    name: microservice-consumer-uploadfile-feign-with-hystrix
  # 配置thymeleaf
  thymeleaf:
    encoding:  UTF-8
    cache: false
    mode: HTML5
  # 分割文件上载大小
  servlet:
    multipart:
      enabled: true  # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    #默認是 false，是否啓動IP訪問
    prefer-ip-address: true
    # 改配置相當與 IP地址:我的應用名稱:端口
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    home-page-url-path: / #/msmupload # microservice-hystrix-turbine3 —— hystrix 对应当前servlet上下文path的监听路径
    health-check-url-path: /actuator/health #/msmupload/actuator/health
    status-page-url-path: /actuator/info #/msmupload/actuator/info
# feign的配置选项
#Hystrix支持，如果为true，hystrix库必须在classpath中
feign.hystrix.enabled: true
#请求和响应GZIP压缩支持
feign.compression.request.enabled: true
feign.compression.response.enabled: true
#支持压缩的mime types
feign.compression.request.mime-types: text/xml,application/xml,application/json
feign.compression.request.min-request-size: 2048
# HTTP 远程调用对开发者完全透明，得到与调用本地方法一致的编码
feign.httpclient.enabled: true
# springboot2.0. 的配置项为: 
management:
  server:
    port: 9005
  endpoints:
    web:
#      base-path: /actuator # 修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  # 开放所有页面节点  默认只开启了health、info两个节点