server:
  port: 8901
# 注册到eureka的应用名称  
spring:
  application:
    name: microservice-hystrix-turbine
# 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
# 默认是http://localhost:8761/eureka ; 多个地址可使用 , 分隔
eureka:
  client:
    service-url:
      default-zone: http://admin:admin@localhost:8761/eureka/
  # 默認是 false，是否啓動IP訪問
  instance:
    prefer-ip-address: true
#springboot2.0. 的配置项为: 
#actuator端口
management:
#  server:
#    port: 9007
  endpoints:
    web:
#      base-path: /monitor #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  # 开放所有页面节点  默认只开启了health、info两个节点
turbine:
  aggregator:
    cluster-config: default     # 需要监控的服务集群名
  #需要监控的应用名
  app-config: microservice-consumer-movie-feign-with-hystrix-hystrix-factory,microservice-consumer-movie-ribbon-with-hystrix-propagating
  cluster-name-expression: new String("default")
#  instanceUrlSuffix:
#      default: actuator/hystrix.stream    # key是clusterConfig集群的名字，value是hystrix监控的后缀，springboot2.0为actuator/hystrix.stream