server:
  port: 8080
# 配置Spring Cloud Config Server 的存储库
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/baiHoo/microservice-config-repo   # 公用仓库
          username: 
          password: 
# springBoot 2.0.3.RELEASE 提供的 security安全机制
  security:
    user:
      name: admin
      password: admin