# 日志操作  
logging:
  pattern:
    level:
      com.baihoo: info
    console: '%d - %msg%n'
# springBoot 2.0.3.RELEASE 后提供的 security安全机制，设置账号密码
spring:
#  security:
#    user:
#      name: admin
#      password: admin
  application:
    # 工程应用名称
    name: EUREKA-HA-SERVER 
# Eureka 高可用配置  
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
---
# Eureka 服务端口配置1
server:
  port: 8761
spring:
  profiles: peer1
# Eureka 配置1  
eureka:
  instance:
    hostname: peer1
---
# Eureka 服务端口配置2
server:
  port: 8762
spring:
  profiles: peer2
# Eureka 配置2
eureka:
  instance:
    hostname: peer2
---
# Eureka 服务端口配置3 
server:
  port: 8763
spring:
  profiles: peer3
# Eureka 配置3  
eureka:
  instance:
    hostname: peer3