server:
  servlet:
    context-path: /msmovie
  port: 7918
logging:
  pattern:
    console: '%d - %msg%n'
    level:
      com.baihoomuch.cloud: info
  # 针对某个类下面的日志级别
  level:
    com.baihoomuch.cloud.microservice.UserFeignClient: debug
spring:
  application:
    name: microservice-consumer-movie-feign-customizing-without-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    #eureka的健康检查  
    healthcheck:
      enabled: true
  instance:
    #默認是 false，是否啓動IP訪問
    prefer-ip-address: true
    # 改配置相當與 IP地址:我的應用名稱:端口
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
# 解决hystrix请求报超时异常的方案：
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
# feign的hystrix, 启用全局断路器模式
feign:
  hystrix:
    enabled: true
#springboot2.0. 以上的配置项为：
#actuator端口
management:
  server:
    port: 9004
  endpoints:
    web:
   #   base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  # 开放所有页面节点  默认只开启了health、info两个节点